### PR TITLE
Update dataset

### PR DESCRIPTION
**Pull request by wallin**
Updated datacenters to reflect this commit: https://github.com/client9/ipcat/commit/d5a4afcd036907ffb236447055d84edbee037466

### CODE REVIEW

**Comment by ktheory** [comment]
Thanks, Sebastian! 👌 I plan to merge & release this in the next few days.

**Comment by wallin** [comment]
Great! thanks. Just noticed that there has been a few more changes, so I updated it to reflect commit:
https://github.com/client9/ipcat/commit/9b650f15cf370974ba779a59456c4fd3f7f47c82

**Comment by ktheory** [comment]
Thanks! :fireworks:

**Comment by ktheory** [comment]
FYI, I released [v2.0.4](https://rubygems.org/gems/ipcat/versions/2.0.4)

**Pull request merged**
